### PR TITLE
fix a bug causing right click to copy a note -- fixes #1833

### LINKED ISSUE #1833: Right clicking on a note in the list copies its link to the clipboard
# Current behavior

Right clicking on a note in the note list copies its link to the clipboard.

# Faulty code

Looks like `copyNoteLink` is called rather than curried at https://github.com/BoostIO/Boostnote/blob/f4024f46836d1aa60e10df05ad1455047cd0bbde/browser/main/NoteList/index.js#L514

The code should probably be:

    click: this.copyNoteLink.bind(null, note)

Or (though `this` context is not required for this function):

    click: this.copyNoteLink.bind(this, note)

Or the `copyNoteLink` function could be refactored to use `this` and state to find the selected note(s) like `deleteNote` and `cloneNote` do.

### PR DESCRIPTION
**Pull request by jacobherrington**
Refs #1833 

This is my first PR to Boostnote, I am happy to hear feedback!

### CODE REVIEW

File: browser/main/NoteList/index.js [hunk 1]
```diff
@@ -684,8 +684,11 @@ class NoteList extends React.Component {
       })
   }
 
-  copyNoteLink (note) {
-    const noteLink = `[${note.title}](:note:${note.key})`
+  copyNoteLink () {
+    const { selectedNoteKeys } = this.state
```
Comment (ZeroX-DG) [inline browser/main/NoteList/index.js]: I think you shouldn't re-find the selected note again because the selected note is already been searched at the top of the `handleNoteContextMenu` function. Please re-use the selected note in the `handleNoteContextMenu` function to improve performance for the app.
