### PR TITLE
convert uml to utf8 before converting to base64

### LINKED ISSUE #1270: UTF8 wrong character when using @startuml
The followin "boostnote" text:

```
@startuml
start
repeat
:Get Username And Password;
note left
Where Presenta la schermata
di login all'utente
end note
if (Username == sAMAccountName) then (yes)
:Check Username And Password 
Against Active Directory;
note left
Il server di Active Directory
è parametrizzato da qualche 
parte su Where
end note
else (no)
:Check Username And Password 
Against Where User Database;
note right
Consueto flusso di 
autenticazione di Where
end note
endif
:Execute Check;
repeat while (Is Password Correct?)
stop
@enduml
```

it is rendered as the attached picture:
screen shot 2017-12-11 at 14 07 50

As you can see, the 'è' char is not interpreted as a valid char.

### PR DESCRIPTION
**Pull request by mslourens**
fixes #1270
Convert the input string to utf-8 with `unescape(encodeURIComponent(umlCode))`, directly copied from [plantUML Web Server](http://www.plantuml.com/plantuml/uml/ZP51JWCn34NtFeLtJA_GggAZAK9TWBf1h4t6qub8an8xBUs9k0SNmpDK55Kis4NEz_VxzaAKifPjWF41cNTC2jDxLdmIpf6sZ7LiSKqYXvJR6SIaZ84xXUUUC-Cwit1Kma0epafRKeBMOqWR7v52k2bg0WOsdw4RV8VLZ_jyZb8_rCwb4lNHAXFKdYDMHvO9J9kUtUlVB0ZrXdmKnTgftpCkVMQdAHz_Kwu2MlEUCnhJjH0-Ft17sPmr-zE9D65B-5OeM184-p8RAJX6lGJW88nLJF_b-zxK8CAbRUU5XC-8sMzwXIP5AMp3kr14qa0AD6xDEphv57aeNKF4rdSmlNjdPr8SGMRd2-AXzy4GLtAXQL8UKjzExDPf1mlhjyD_0G00): 
```javascript
function compress(s, change) {
  //UTF8
  s = unescape(encodeURIComponent(s));
  dest = "http://www.plantuml.com/plantuml" + "/uml/"+encode64(zip_deflate(s, 9));
  if (change) dest += "?switch";
  window.location.href = dest;
}
```

### CODE REVIEW

File: browser/lib/markdown.js [hunk 1]
```diff
@@ -76,7 +76,16 @@ md.use(require('markdown-it-named-headers'), {
   }
 })
 md.use(require('markdown-it-kbd'))
-md.use(require('markdown-it-plantuml'))
+md.use(require('markdown-it-plantuml'), '', {
+  generateSource: function (umlCode) {
+    var deflate = require('markdown-it-plantuml/lib/deflate')
```
Comment (sota1235) [inline browser/lib/markdown.js]: pleze do not use dynamic import. `.mjs` don't support dynamic import.(because `.mjs` loading is async)

Comment (mslourens) [reply browser/lib/markdown.js]: what do you mean by .mjs? The deflate script is just a normal .js file...

Comment (sota1235) [reply browser/lib/markdown.js]: `.mjs` means next feature of ecmascript.
fyi -> https://docs.google.com/presentation/d/1JKnj-HvAwkba9GMEuEqZjMPzAaZTL7j2f1n4JjOWXhs/edit#slide=id.p

**Comment by kazup01** [comment]
Merged. Thanks @mslourens .
