### PR TITLE
fix reload crash on /searched

### LINKED ISSUE #1743: Search and Reload fail to reload
### Reproduce steps

1. Input Search keyword
2. Realod
3. Throw error

```
react-dom.min.js:13 Uncaught TypeError: Cannot read property '__reactInternalInstance$uu9ekz18zj' of null
    at Object.u [as getClosestInstanceFromNode] (react-dom.min.js:13)
    at r (react-dom.min.js:14)
    at i (react-dom.min.js:14)
    at r.perform (react-dom.min.js:15)
    at Object.batchedUpdates (react-dom.min.js:14)
    at Object.i [as batchedUpdates] (react-dom.min.js:14)
    at dispatchEvent (react-dom.min.js:14)
```

### Details

When first routing, `document.getElementsByClassName('searchInput')[0]` is `undefined`.

https://github.com/BoostIO/Boostnote/blob/80d1ca81acc38926cbd3f421feb7529b0001c339/browser/main/NoteList/index.js#L328-L330

### PR DESCRIPTION
**Pull request by azu**
This PR fix reloading creash on `/searched` #1743

Add routing for search word:

- `/searched/:searchword`

Restore the state from the `:searchword` params.

fix #1743

### CODE REVIEW

File: browser/main/TopBar/index.js [hunk 1]
```diff
@@ -28,6 +28,14 @@ class TopBar extends React.Component {
   }
 
   componentDidMount () {
+    const { params } = this.props
+    const searchWord = params.searchword
+    if (searchWord !== undefined) {
+      this.setState({
```
Comment (azu) [inline browser/main/TopBar/index.js]: Restore `search` state from `/searched/:searchword`

File: browser/main/TopBar/index.js [hunk 2]
```diff
@@ -97,9 +105,10 @@ class TopBar extends React.Component {
       this.setState({
         isConfirmTranslation: true
       })
-      router.push('/searched')
+      const keyword = this.refs.searchInput.value
+      router.push(`/searched/${encodeURIComponent(keyword)}`)
```
Comment (azu) [inline browser/main/TopBar/index.js]: push to `/searched/:searchword`

File: browser/main/index.js [hunk 3]
```diff
@@ -64,7 +64,9 @@ ReactDOM.render((
         <IndexRedirect to='/home' />
         <Route path='home' />
         <Route path='starred' />
-        <Route path='searched' />
+        <Route path='searched'>
+          <Route path=':searchword' />
```
Comment (azu) [inline browser/main/index.js]: `/searched/:searchword`

File: browser/main/NoteList/index.js [hunk 4]
```diff
@@ -326,8 +326,10 @@ class NoteList extends React.Component {
     }
 
     if (location.pathname.match(/\/searched/)) {
-      const searchInputText = document.getElementsByClassName('searchInput')[0].value
```
Comment (azu) [inline browser/main/NoteList/index.js]: This is the crash reason #1743
