### PR TITLE
Fix regular expression related checkbox logic

### LINKED ISSUE #2829: Checkbox does not work correctly in quotation
[Issuehunt badges](https://issuehunt.io/r/BoostIo/Boostnote/issues/2829)

# Current behavior
When creating a checkbox inside a quotation then the checkbox becomes unclickable.

# Expected behavior
The checkbox should be clickable in a quotation.

# Steps to reproduce

Markdown:
```
# Tasks
- [ ] `Do something`
> - [_] `Style for more lines`
> Some more lines  
```
reproduced_bug

Boostnote Editor automatically adds an underscore into the brackets when using quotation
`> - [_]`

# Environment

- Version :  Boostnote 0.11.12
- OS Version and name : macOs Sierra 10.12.6

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Sponsors (Total: $20.00)

- [boostio boostio](https://issuehunt.io/u/boostio) ($20.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/BoostIo/Boostnote/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### PR DESCRIPTION
**Pull request by mpls104**
evidence

## Description
As described in issue, checkbox was unclickable in quotation.
Fixed regular expression on checkbox logic and added some test patterns.

This is my first contribution to OSS in my life. :smile: 
Please kindly point out if there is something wrong 🙏 

## Issue fixed
#2829

## Type of changes

- :radio_button: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :white_circle: Improvement (Change that improves the code. Maybe performance or development improvement)
- :white_circle: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- :radio_button: My code follows [the project code style](docs/code_style.md)
- :radio_button: I have written test for my code and it has been tested
- :radio_button: All existing tests have been passed
- :radio_button: I have attached a screenshot/video to visualize my change if possible

### CODE REVIEW

**Comment by ZeroX-DG** [comment]
I'm gonna be criticizing as hard as I can :rofl:

**Comment by ZeroX-DG** [comment]
It currently doesn't work for a nested quote like this. I don't know if we should support it.
image

**Comment by mpls104** [comment]
Thank you for checking precisely  😄 
I think it's better to support this and done some changes.
What do you think @ZeroX-DG ?

**Comment by ZeroX-DG** [comment]
Well, I'll need confirmation from the "higher" power @Rokt33r

**Comment by AWolf81** [comment]
LGTM.

Just one thing I've noticed is that sub-elements are striked through if the top element is checked. I think you haven't introduced the issue but it's a bit weird and it would be probably better to not have them striked as they're not handled in the action item done count. See screenshot below, everything seems done but the counter says 60%.
But I think we could improve that in a separate PR if it's difficult to fix.

grafik

I'll have a look at your regex updates in a minute and leave an inline comment if there is something to improve.

File: browser/components/MarkdownEditor.js [hunk 1]
```diff
@@ -159,10 +159,10 @@ class MarkdownEditor extends React.Component {
     e.preventDefault()
     e.stopPropagation()
     const idMatch = /checkbox-([0-9]+)/
-    const checkedMatch = /^\s*[\+\-\*] \[x\]/i
-    const uncheckedMatch = /^\s*[\+\-\*] \[ \]/
-    const checkReplace = /\[x\]/i
-    const uncheckReplace = /\[ \]/
+    const checkedMatch = /^(\s*>?)*\s*[+\-*] \[x]/i
+    const uncheckedMatch = /^(\s*>?)*\s*[+\-*] \[ ]/
```
Comment (AWolf81) [inline browser/components/MarkdownEditor.js]: I've first thought there are missing escape sequences in the regex but I think it's OK to omit them.
I did a quick test in the following [regex101](https://regex101.com/r/LzQcdc/2) - just wondering why the nested checkboxes are not matching there.
Is it because in Boostnote it is running in a loop or do I have a mistake in the regex101 test patterns?

**Comment by ZeroX-DG** [comment]
@AWolf81 The nested checkbox is strikethrough is because of the CSS property
```
text-decoration: line-through;
```

If that CSS property is applied to the parent element, the children element will be affected too which is a bit weird. You're right, it should be solved in a separated issue, it may be difficult to solve.

**Comment by arcturus140** [comment]
i think this strike through behaviour is intended, but I also think it is weird 😣

File: browser/components/MarkdownEditor.js (hunk 1 above)
Comment (arcturus140) [reply browser/components/MarkdownEditor.js]: it's a line pattern and only matched the first occurrence

**Comment by Rokt33r** [comment]
LGTM. And I'm also thinking it is a bit weird. Let's fix it in other pr.
