### PR TITLE
OnBlur throws exceptions if the notetype is snippet -> Fixes #1962

### LINKED ISSUE #1962: [Bug] OnBlur throws exceptions if the notetype is snippet
... in that case the storageKey passed to the method is undefined -> Errors

### PR DESCRIPTION
**Pull request by ehhc**
I've only inserted an additional IF..

### CODE REVIEW

File: browser/main/lib/dataApi/attachmentManagement.js [hunk 1]
```diff
@@ -232,39 +232,41 @@ function deleteAttachmentFolder (storageKey, noteKey) {
...
  */
 function deleteAttachmentsNotPresentInNote (markdownContent, storageKey, noteKey) {
-  const targetStorage = findStorage.findStorage(storageKey)
-  const attachmentFolder = path.join(targetStorage.path, DESTINATION_FOLDER, noteKey)
-  const attachmentsInNote = getAttachmentsInContent(markdownContent)
-  const attachmentsInNoteOnlyFileNames = []
-  if (attachmentsInNote) {
-    for (let i = 0; i < attachmentsInNote.length; i++) {
-      attachmentsInNoteOnlyFileNames.push(attachmentsInNote[i].replace(new RegExp(STORAGE_FOLDER_PLACEHOLDER + escapeStringRegexp(path.sep) + noteKey + escapeStringRegexp(path.sep), 'g'), ''))
+  if (storageKey && noteKey && markdownContent !== null && typeof markdownContent !== 'undefined') {
```
Comment (sosukesuzuki) [inline browser/main/lib/dataApi/attachmentManagement.js]: please write like below: 
```Javascript
if (storageKey != null && noteKey != null && markdownContent != null)
```

Comment (ehhc) [reply browser/main/lib/dataApi/attachmentManagement.js]: you are right and i've fixed the issue like you suggested

**Comment by ehhc** [comment]
@sosukesuzuki i've changed it like you said ;)

File: browser/main/lib/dataApi/attachmentManagement.js [hunk 2]
```diff
@@ -245,39 +245,41 @@ function deleteAttachmentFolder (storageKey, noteKey) {
...
  */
 function deleteAttachmentsNotPresentInNote (markdownContent, storageKey, noteKey) {
-  const targetStorage = findStorage.findStorage(storageKey)
-  const attachmentFolder = path.join(targetStorage.path, DESTINATION_FOLDER, noteKey)
-  const attachmentsInNote = getAttachmentsInContent(markdownContent)
-  const attachmentsInNoteOnlyFileNames = []
-  if (attachmentsInNote) {
-    for (let i = 0; i < attachmentsInNote.length; i++) {
-      attachmentsInNoteOnlyFileNames.push(attachmentsInNote[i].replace(new RegExp(STORAGE_FOLDER_PLACEHOLDER + escapeStringRegexp(path.sep) + noteKey + escapeStringRegexp(path.sep), 'g'), ''))
+  if (storageKey != null && noteKey != null && markdownContent != null) {
```
Comment (sosukesuzuki) [inline browser/main/lib/dataApi/attachmentManagement.js]: It might be better for this to be able to reduce nesting, like below:
```javascript
if (storageKey == null || noteKey == null || markdownContent == null) return
```

Comment (ehhc) [reply browser/main/lib/dataApi/attachmentManagement.js]: done

File: browser/main/lib/dataApi/attachmentManagement.js [hunk 3]
```diff
@@ -245,41 +245,41 @@ function deleteAttachmentFolder (storageKey, noteKey) {
...
-  if (storageKey != null && noteKey != null && markdownContent != null) {
-    const targetStorage = findStorage.findStorage(storageKey)
-    const attachmentFolder = path.join(targetStorage.path, DESTINATION_FOLDER, noteKey)
-    const attachmentsInNote = getAttachmentsInContent(markdownContent)
-    const attachmentsInNoteOnlyFileNames = []
-    if (attachmentsInNote) {
-      for (let i = 0; i < attachmentsInNote.length; i++) {
-        attachmentsInNoteOnlyFileNames.push(attachmentsInNote[i].replace(new RegExp(STORAGE_FOLDER_PLACEHOLDER + escapeStringRegexp(path.sep) + noteKey + escapeStringRegexp(path.sep), 'g'), ''))
-      }
+  if (storageKey == null || noteKey == null || markdownContent == null) {
```
Comment (sosukesuzuki) [inline browser/main/lib/dataApi/attachmentManagement.js]: `{}` is unnecessary.please write like below:
```javascript
if (storageKey == null || noteKey == null || markdownContent == null) return
```
