### PR TITLE
Fix the shift selection and ctrl selection in note list

### LINKED ISSUE #1975: Shift Key is not a Ctrl Key
# Current behavior

When selecting multiple notes, the Shift Key behaves as if it was a Ctrl Key and selects the entries one by one.

# Expected behavior

Shift should select all notes between the first one selected and the last one selected.

### PR DESCRIPTION
**Pull request by richardtks**
## Description
There are two behaviors being changed:
1. When user click on the notes 
     a. Shift - It will select the notes among the first and the last note
     b. Ctrl - it will only select the selected note
2. When user uses the arrow keys
    a. Shift - it will extends the selection from the last selected note
    b. Ctrl - Nothing will happens

## Issue fixed
#1975 

## Type of changes

- :white_circle: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :radio_button: Improvement (Change that improves the code. Maybe performance or development improvement)
- :white_circle: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- :radio_button: My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- :radio_button: All existing tests have been passed
- :white_circle: I have attached a screenshot/video to visualize my change if possible

### CODE REVIEW

File: browser/main/NoteList/index.js [hunk 1]
```diff
@@ -390,25 +398,51 @@ class NoteList extends React.Component {
...
       selectedNoteKeys = []
     }
     selectedNoteKeys.push(uniqueKey)
+
+    if (shiftKeyDown && selectedNoteKeys.length > 0) {
+      const firstSelectedNoteIndex =
+        Math.max(this.getNoteIndexByKey(selectedNoteKeys[0]),
+        this.state.firstShiftSelectedNoteIndex)
+      const lastSelectedNoteIndex = this.getNoteIndexByKey(uniqueKey)
+      const startIndex = Math.min(firstSelectedNoteIndex, lastSelectedNoteIndex)
```
Comment (ZeroX-DG) [inline browser/main/NoteList/index.js]: I think a simple ternary operator will be faster than using math function.
```suggestion
      const startIndex = firstSelectedNoteIndex < lastSelectedNoteIndex ? firstSelectedNoteIndex : lastSelectedNoteIndex
```

File: browser/main/NoteList/index.js [hunk 2]
```diff
@@ -390,25 +398,51 @@ class NoteList extends React.Component {
...
+      const endIndex = Math.max(firstSelectedNoteIndex, lastSelectedNoteIndex)
```
Comment (ZeroX-DG) [inline browser/main/NoteList/index.js]: Github suggestion is so cool :smile: 
```suggestion
      const endIndex = firstSelectedNoteIndex > lastSelectedNoteIndex ? firstSelectedNoteIndex : lastSelectedNoteIndex
```

File: browser/main/NoteList/index.js (hunk 1 above)
Comment (richardtks) [reply browser/main/NoteList/index.js]: Updated

File: browser/main/NoteList/index.js (hunk 2 above)
Comment (richardtks) [reply browser/main/NoteList/index.js]: Updated
