### PR TITLE
Issue 2858 - Will no longer attempt to redraw images that are already of the correct rotation

### LINKED ISSUE #2858: Attached image files grow in size and get corrupted meta info
# Current behavior

When you drag an image file into a note, boostnote creates a new file in `{storage_folder}\attachments\{note_id}\{some_hash}.jpg` and insert a link to it. The problem is that new file size appears few times bigger than original one and its image metadata is corrupted (or deleted):

Original file is **1.05 MB** and has some usual image meta info:
image

Attached file is **9.13 MB** and all meta is missed:
image
More over some programs like embedded window image viewer even don't recognize this file as an image.

# Expected behavior

When I attach a file I expect it to be untouched (same file size, same meta info etc).

# Steps to reproduce

1. Drag'n'drop a JPG file into a note
2. Compare attached file to original one

# Environment

- Version : 0.11.13
- OS Version and name : Windows 10

### PR DESCRIPTION
**Pull request by MiloTodt**
## Description

Currently, Boostnote calls a "fixRotate" function on all dropped images. This works by creating a canvas, redrawing the image, and then saving the canvas. This means that all images were being saved as base64, which inflated filesizes.

This fix makes it so that any image that is already of the correct rotation (the vast majority of them) does not go through the fixRotate call, and their filesize does not increase.

Before import:

During import (the console.logs have been removed before submission):

After importing the pictures and exporting the note. The filesize of the image that had correct rotation in the first place is not changed. Note how the one which had the wrong rotation has grown.

## Issue fixed
fix #2858

## Type of changes

- ✔️ Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :white_circle: Improvement (Change that improves the code. Maybe performance or development improvement)
- :white_circle: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- ✔️ My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- ✔️ All existing tests have been passed
- ✔️ I have attached a screenshot/video to visualize my change if possible

### CODE REVIEW

File: browser/main/lib/dataApi/attachmentManagement.js [hunk 1]
```diff
@@ -286,13 +287,24 @@ function handleAttachmentDrop (codeEditor, storageKey, noteKey, dropEvent) {
             isImage: true
           }))
         } else {
-          return fixRotate(file)
-            .then(data => copyAttachment({type: 'base64', data: data, sourceFilePath: file.path}, storageKey, noteKey)
-              .then(fileName => ({
+          return getOrientation(file)
+            .then((orientation) => {
+              if (orientation === -1) { // The image rotation is correct and does not need adjustment
+                return copyAttachment(file.path, storageKey, noteKey)
```
Comment (ZeroX-DG) [inline browser/main/lib/dataApi/attachmentManagement.js]: Can you change it to `filePath` too? Thanks!

Comment (MiloTodt) [reply browser/main/lib/dataApi/attachmentManagement.js]: Change made as requested, alongside the same change in other parts of the function. Retested with same images.

**Comment by MiloTodt** [comment]
The pipeline is failing, but I don't think it's my code doing it? Yarn isn't able to find a package on the test server. 
image
