### PR TITLE
Fix #888 - Wrong word count due splitting

### LINKED ISSUE #888: Word and letter count are wrong
# context
It only counts spaces so it shows us 1 as the word count if the note has only line breaks instead of spaces.

image
(there's no error)

### PR DESCRIPTION
**Pull request by thamara**
## Description
Word count on Note Details was incorrect computed by counting words splitted by space. In the event of one word per line, the count was incorrect:

wrong word count

This was fixed by converting line breaks into spaces and then splitting them for count:

correct word count

## Issue fixed
#888 

## Type of changes

- :black_circle: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :white_circle: Improvement (Change that improves the code. Maybe performance or development improvement)
- :white_circle: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- :black_circle: My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- :white_circle: All existing tests have been passed
- :black_circle: I have attached a screenshot/video to visualize my change if possible

### CODE REVIEW

File: browser/main/Detail/MarkdownNoteDetail.js [hunk 1]
```diff
@@ -511,7 +511,7 @@ class MarkdownNoteDetail extends React.Component {
           exportAsTxt={this.exportAsTxt}
           exportAsHtml={this.exportAsHtml}
           exportAsPdf={this.exportAsPdf}
-          wordCount={note.content.split(' ').length}
+          wordCount={note.content.replace(/\r?\n?\s+/g, ' ').trim().split(' ').length}
```
Comment (chrjean) [inline browser/main/Detail/MarkdownNoteDetail.js]: Hello ! :)

I think it can be replaced by:

`note.content.trim().split(/\r?\n?\s+/g).length`

or even

`note.content.trim().split(/\s+/g).length`
since `\s` includes cariage returns and new lines

https://www.w3schools.com/jsref/jsref_regexp_whitespace.asp

Comment (ZeroX-DG) [reply browser/main/Detail/MarkdownNoteDetail.js]: @thamara Can you change your code to the above suggestion for more concise code?  Thanks.

Comment (AWolf81) [reply browser/main/Detail/MarkdownNoteDetail.js]: Good point. I'd use the `split(/s+/g)`.

https://repl.it/@alexanderwolf/Word-count-regex

Comment (thamara) [reply browser/main/Detail/MarkdownNoteDetail.js]: I'll make the suggested change. Thanks!
